### ISSUE TITLE
[Bug] "DOMParser is not defined"

### ISSUE THREAD

**Issue by KaKi87** [jsbenchmark/jsbenchmark#4]
Hi,

[`DOMParser`](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) is a standard JS API, but it's not working in jsbenchmark.com :

> DOMParser is not defined

Thanks

**Comment by pabueco** [comment]
Hi, unfortunately the `DOMParser` is not available in web workers, which is where the benchmarks are run.

However you can use external libraries like [`linkedom`](https://github.com/WebReflection/linkedom), that provide a very similar API and functionality to the native `DOMParser`. Here's an [example REPL](https://jsbenchmark.com/repl#eyJjb25maWciOnsibmFtZSI6IkJhc2ljIGV4YW1wbGUiLCJ0ZXN0Ijp7ImRlcGVuZGVuY2llcyI6W3sidXJsIjoiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9saW5rZWRvbUAwLjE2LjExLytlc20iLCJuYW1lIjoibGlua2Vkb20iLCJlc20iOnRydWV9XSwiY29kZSI6ImNvbnN0IHsgRE9NUGFyc2VyIH0gPSBsaW5rZWRvbTtcblxuY29uc3QgSFRNTCA9IGBcbiAgPCFkb2N0eXBlIGh0bWw-XG4gIDxodG1sIGxhbmc9XCJlblwiPlxuICAgIDxoZWFkPlxuICAgICAgPHRpdGxlPkhlbGxvIFdvcmxkPC90aXRsZT5cbiAgICA8L2hlYWQ-XG4gICAgPGJvZHk-XG4gICAgICA8Zm9ybT5cbiAgICAgICAgPGlucHV0IG5hbWU9XCJ1c2VyXCI-XG4gICAgICAgIDxidXR0b24-XG4gICAgICAgICAgU3VibWl0IE9uZVxuICAgICAgICA8L2J1dHRvbj5cbiAgICAgIDwvZm9ybT5cblxuICAgICAgPGJ1dHRvbj5cbiAgICAgICAgU3VibWl0IFR3b1xuICAgICAgPC9idXR0b24-XG4gICAgPC9ib2R5PlxuICA8L2h0bWw-XG5gXG5cbi8vIFVzaW5nIERPTVBhcnNlclxuY29uc3QgcGFyc2VyID0gbmV3IERPTVBhcnNlcigpO1xuY29uc3QgZG9jdW1lbnQgPSBwYXJzZXIucGFyc2VGcm9tU3RyaW5nKEhUTUwpO1xuY29uc3QgYnV0dG9ucyA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3JBbGwoJ2J1dHRvbicpXG5cbkxPRyhidXR0b25zLm1hcChiID0-IGIudGV4dENvbnRlbnQudHJpbSgpKSkifX19). The performance likely won't be exactly the same as the native one, but it should be enough to compare different approaches/snippets.
