### ISSUE TITLE
Measurement bottleneck on small benchmarks

### ISSUE THREAD

**Issue by kade-robertson** [jsbenchmark/jsbenchmark#7]
If you have a benchmark with test cases that run very quickly, you can't get an idea of the performance difference because they all seem to hit the same "ceiling" in ops/s.

Take these trivial cases: https://jsbm.dev/hEJNNQQm5WzIR

On my machine, in Firefox these all hit ~3.7m ops/s, and on Chrome they hit ~4.8m ops/sec. In reality, these test cases run even faster -- if I run the same cases in https://jsbench.me/ for example ([link](https://jsbench.me/5ilvv32cmt/1)), these are at least 2 orders of magnitude faster in terms of ops/s. I'm not sure if this is just an inherent trade-off of the worker approach.

I did a bit of profiling and noticed that in the case of these tiny benchmarks that `performance.now` contributes to a large amount of the runtime:
![image](https://github.com/jsbenchmark/jsbenchmark/assets/8824774/7068d4c0-71df-4667-ba3e-24754b99968c)

Whereas for jsbench, it seems to use `Date.now` for measuring which doesn't even show up on the chart. I have tried a few things but nothing I do is able to close the gap (all measured in Firefox, independent of one another):

- Swap `performance.now` for `Date.now` is only slightly (3.7m ops/s -> 4.1m ops/s) faster and is still a significant proportion of the measurements.
- Use a synchronous function for running the code gave a decent bump (3.7m ops/s -> 6.2m ops/s)
- Reduce `performance.now()` calls by only checking for time limit every 1,000 iterations gave another bump (3.7m ops/s -> 5.2m ops/s)

If I make all the above changes I can hit around 10m ops/s, but it's still nowhere near something like jsbench.

Edit: With some more experimenting I think there is some worker overhead but not that much -- see https://jsbm.dev/WjgHnhqJhhBXv, where I run each benchmark 100 times, on my machine I'm finally able to see some performance difference between the first test case and the rest. If I bump it up to 1000 times, I can see even more differentiation. Doing the math backwards I don't quite get to the numbers of jsbench but it's at least within the same order of magnitude

**Comment by kade-robertson** [comment]
So I had a bit of a goof and switching from an async function to a sync function actually brings the difference MUCH closer, as it turns out even a useless `await` on a synchronous function would still slow this down quite a bit. With all of the changes from above applied I get fairly close (only 4-5x worse than jsbench):
![basic-example(1)](https://github.com/jsbenchmark/jsbenchmark/assets/8824774/941a5fc2-9a61-4083-8783-d6d6b55ca6f9)

**Comment by pabueco** [comment]
So I finally had some time to look into this.

I implemented your suggestions/ideas (with a few modifications) in [this PR](https://github.com/jsbenchmark/jsbenchmark/pull/8) and the ops/s went from ~5m to ~725m, and much closer to jsbench. You can also now actually tell a difference between the different cases without adding loops to the individual tests.

![basic-example (6)](https://github.com/jsbenchmark/jsbenchmark/assets/25956751/7d0a0408-2d90-4895-a42f-0f48ef95f6e9)

The changes are not yet live, but you can preview and test them [here](https://vercel.live/open-feedback/jsbenchmark-git-performance-improvements-pabueco.vercel.app?via=pr-comment-visit-preview-link&passThrough=1).

Thanks again for your investigation! 🫶

**Comment by kade-robertson** [comment]
Awesome, looks great!

**Comment by pabueco** [comment]
Fixed by https://github.com/jsbenchmark/jsbenchmark/pull/8
